---
- name: Copy over keybindings
  become: yes
  become_user: "{{ user.username }}"
  template:
    src: kglobalshortcutsrc
    dest: ~/.config/kglobalshortcutsrc
    owner: "{{ user.username }}"
    mode: 0600
