- name: Download krohnkite script
  get_url:
    url: https://github.com/anametologin/krohnkite/releases/download/0.9.8.2/krohnkite-0.9.8.2.kwinscript
    dest: /tmp/krohnkite.kwinscript
    mode: 0777

- name: Check if krohnkite is already installed
  become: yes
  become_user: "{{ user.username }}"
  command: |
    kpackagetool6 -t KWin/Script -l
  register: kpackages

- name: Update krohnkite
  become: yes
  become_user: "{{ user.username }}"
  command: |
    kpackagetool6 -t KWin/Script -u /tmp/krohnkite.kwinscript
  when: '"krohnkite" in kpackages.stdout'

- name: Install krohnkite
  become: yes
  become_user: "{{ user.username }}"
  command: |
    kpackagetool6 -t KWin/Script -i /tmp/krohnkite.kwinscript
  when: '"krohnkite" not in kpackages.stdout'
