---
# tasks file for kde

- name: Install KDE desktop packages
  include: "install_{{ ansible_os_family }}.yml"

- name: Setup virtual desktops
  include: "virtual_desktops.yml"
  vars:
    user: "{{ desktop_user }}"

- name: Setup window rules
  include: "window_rules.yml"
  vars:
    user: "{{ desktop_user }}"

- name: Setup keybindings
  include: "keybindings.yml"
  vars:
    user: "{{ desktop_user }}"

- name: Setup Konsole
  include: "konsole.yml"
  vars:
    user: "{{ desktop_user }}"
