---
- name: Setup 4 virtual desktops
  become: yes
  become_user: "{{ user.username }}"
  blockinfile:
    path: "~/.config/kwinrc"
    owner: "{{ user.username }}"
    block: |
      [Desktop]
      Name_1=Web
      Name_2=Dev
      Name_3=Comm
      Name_4=Games
      Number=4
      Rows=4
