---
# All rules reside in kwinrulesrc

- name: Setup Konsole rules
  become: yes
  become_user: "{{ user.username }}"
  blockinfile:
    path: "~/.config/kwinrulesrc"
    owner: "{{ user.username }}"
    block: |
      [1]
      Description=Window settings for konsole
      desktop=-1
      desktoprule=3
      title={{ user.username }} : zsh — Konsole
      titlematch=0
      types=1
      windowrole=mainwindow#1
      windowrolematch=1
      wmclass=konsole
      wmclasscomplete=false
      wmclassmatch=1

- name: Setup Emacs rules
  become: yes
  become_user: "{{ user.username }}"
  blockinfile:
    path: "~/.config/kwinrulesrc"
    owner: "{{ user.username }}"
    block: |
      [2]
      Description=Window settings for emacs
      desktop=2
      desktoprule=3
      maximizehoriz=true
      maximizehorizrule=3
      maximizevert=true
      maximizevertrule=3
      screen=0
      screenrule=3
      types=1
      wmclass=emacs25 emacs
      wmclasscomplete=true
      wmclassmatch=1

- name: Setup Firefox rules
  become: yes
  become_user: "{{ user.username }}"
  blockinfile:
    path: "~/.config/kwinrulesrc"
    owner: "{{ user.username }}"
    block: |
      [3]
      Description=Application settings for firefox
      desktop=1
      desktoprule=3
      wmclass=navigator firefox
      wmclasscomplete=true
      wmclassmatch=1

- name: Setup steam rules
  become: yes
  become_user: "{{ user.username }}"
  blockinfile:
    path: "~/.config/kwinrulesrc"
    owner: "{{ user.username }}"
    block: |
      [4]
      Description=Application settings for steam
      desktop=4
      desktoprule=3
      wmclass=steam
      wmclasscomplete=false
      wmclassmatch=1
