---
# All rules reside in kwinrulesrc

- name: Copy over window rules
  become: yes
  become_user: "{{ user.username }}"
  template:
    src: kwinrulesrc.kwinrule
    dest: "~/.config/kwinrulesrc"
    owner: "{{ user.username }}"
    mode: 0600
