---

- name: Install rbenv (user only)
  become: yes
  become_user: "{{ user.username }}"
  git:
    dest: "~/.rbenv"
    repo: https://github.com/rbenv/rbenv.git

- name: Check rbenv-plugins directory exists.
  become: yes
  become_user: "{{ user.username }}"
  stat:
    path: "~/.rbenv/plugins"
  register: file_details

- debug:
    var: file_details

- name: Create rbenv-plugins directory
  become: yes
  become_user: "{{ user.username }}"
  file:
    path: "~/.rbenv/plugins"
    state: directory
    owner: "{{ user.username }}"
  when: not file_details.stat.exists

- name: Install ruby-build
  become: yes
  become_user: "{{ user.username }}"
  git:
    dest: "~/.rbenv/plugins/ruby-build/"
    repo: https://github.com/rbenv/ruby-build.git