---
- name: Download the rustup installer
  get_url:
    dest: /tmp/rustup.sh
    url:  https://sh.rustup.rs
    mode: 0755

- name: Install the rustup toolchain for the user
  become: yes
  become_user: "{{ desktop_user.username }}"
  command: /tmp/rustup.sh -y

- name: Add .cargo/bin to PATH
  become: yes
  become_user: "{{ desktop_user.username }}"
  lineinfile:
    dest: "~/.zshenv"
    line: 'PATH="$HOME/.cargo/bin:$PATH"'
    insertafter: "# PATH config:"

- name: Install rust completions
  become: yes
  become_user: "{{ desktop_user.username }}"
  shell: ~/.cargo/bin/rustup completions zsh > ~/.zfunctions/_rustup

- name: Install toolchain
  become: yes
  become_user: "{{ desktop_user.username }}"
  command: ~/.cargo/bin/rustup install stable

- name: Set default toolchain
  become: yes
  become_user: "{{ desktop_user.username }}"
  command: "~/.cargo/bin/rustup default stable-x86_64-unknown-linux-gnu"

- name: Install dev components
  become: yes
  become_user: "{{ desktop_user.username }}"
  command: ~/.cargo/bin/rustup component add rls rustfmt
