#!/usr/bin/zsh -f
# Kill all running containers.
alias dockerkillall='docker kill $(docker ps -q)'

# Delete all stopped containers.
alias dockercleanc='printf "\n>>> Deleting stopped containers\n\n" && docker rm $(docker ps -a -q)'

# Delete all untagged images.
alias dockercleani='printf "\n>>> Deleting untagged images\n\n" && docker rmi $(docker images -q -f dangling=true)'

# Delete all stopped containers and untagged images.
alias dockerclean='dockercleanc || true && dockercleani'

# Clean up no longer used volumes
alias dockercleanvol='printf "\n>>> Deleting unused volumes\n\n" && docker volume ls -qf dangling=true | xargs -r docker volume rm'

alias emacs='TERM=xterm-direct emacs -nw $*'

alias k='kubectl'

# Quick access emacsclient
alias e='TERM=xterm-direct emacsclient $*'
alias ae='TERM=xterm-direct emacsclient -n $*'

function light-theme() {
  kitty +kitten themes --reload-in=all 'Atom One Light'
  gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita'
  gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
  if pgrep 'emacs' > /dev/null; then
    emacsclient -e "(load-theme 'doom-one-light :no-confirm)"
  fi
}

function dark-theme() {
  kitty +kitten themes --reload-in=all 'Dracula'
  gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
  gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
  if pgrep 'emacs' > /dev/null; then
    emacsclient -e "(load-theme 'doom-one :no-confirm)"
  fi
}

function yaml-to-json () {
  SCRIPT="\
#!/usr/bin/env python3

import os
import sys
import json
import yaml

arg = sys.argv[1]

if os.path.isfile(arg):
    content = open(arg).read()
else:
    content = arg

d = yaml.safe_load(content)
print(json.dumps(d))"
  python -c "$SCRIPT" "$1"
}

function json-to-yaml () {
  SCRIPT="\
#!/usr/bin/env python3

import os
import sys
import json
import yaml

arg = sys.argv[1]

if os.path.isfile(arg):
    content = open(arg).read()
else:
    content = arg

d = json.loads(arg)
print(yaml.dump(d))"
  python -c "$SCRIPT" "$1"
}

function url-unquote () {
  python3 -c "from urllib import parse; print(parse.unquote('$1'))"
}

function url-quote () {
  python3 -c "from urllib import parse; print(parse.quote('$1'))"
}

function decode-jwt () {
  jq -R 'split(".") | .[0],.[1] | @base64d | fromjson' <<< "$1"
}
