---
- name: Install the hyprland window manager
  package:
    name:
      - wlsunset
      - light
      - mako
      - hyprland
      - waybar
      - wl-clipboard
      - wofi
      - network-manager-applet
    state: present

- name: Create the hyprland & waybar configuration folder
  become: yes
  become_user: "{{ desktop_user.username }}"
  file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ desktop_user.username }}"
  with_items:
    - "~/.config/hypr"
    - "~/.config/waybar"

- name: Copy over the hyprland configuration
  become: yes
  become_user: "{{ desktop_user.username }}"
  template:
    src: "hyprland.conf"
    dest: "~/.config/hypr/hyprland.conf"
    owner: "{{ desktop_user.username }}"
    mode: 0644

- name: Copy over the sway configuration
  become: yes
  become_user: "{{ desktop_user.username }}"
  template:
    src: "{{ item }}"
    dest: "~/.config/waybar/{{ item }}"
    owner: "{{ desktop_user.username }}"
    mode: 0644
  with_items:
    - "waybar-hyprland.conf"
    - "style.css"
    - "machiatto.css"
