---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ k8s_foundryvtt_pvc_name }}"
  namespace: "{{ k8s_foundryvtt_namespace }}"
spec:
  storageClassName: "{{ k8s_storageclass_name }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ k8s_foundry_storage_size }}"
