---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foundryvtt
  namespace: "{{ k8s_foundryvtt_namespace }}"
  annotations:
    kubernetes.io/ingress.class: public
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: 64m
spec:
  rules:
    - host: "{{ k8s_ingress_hostname }}"
      http:
        paths:
          - path: "/foundry"
            pathType: "Prefix"
            backend:
              service:
                name: foundryvtt-web
                port:
                  number: 80
  tls:
    - hosts:
        - "{{ k8s_ingress_hostname }}"
      secretName: foundryvtt-web-tls-cert
