---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: foundryvtt
  namespace: "{{ k8s_foundryvtt_namespace }}"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # "letsencrypt-prod"
spec:
  rules:
    - host: "{{ k8s_ingress_hostname }}"
      http:
        paths:
          - path: "/foundry"
            backend:
              serviceName: foundryvtt-web
              servicePort: 80
  tls:
    - hosts:
        - "{{ k8s_ingress_hostname }}"
      secretName: foundryvtt-web-tls-cert
