---

- name: Install flatpak
  package:
    name: flatpak
    state: present

- name: Add flathub remote
  become: yes
  become_user: "{{ desktop_user.username }}"
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
    method: user

- name: Install spotify flatpak
  become: yes
  become_user: "{{ desktop_user.username }}"
  flatpak:
    name: "com.spotify.Client"
    state: present
    method: user

- name: Install riot flatpak
  become: yes
  become_user: "{{ desktop_user.username }}"
  flatpak:
    name: "im.riot.Riot"
    state: present
    method: user

- name: Install foliate flatpak
  become: yes
  become_user: "{{ desktop_user.username }}"
  flatpak:
    name: "com.github.johnfactotum.Foliate"
    state: present
    method: user

- name: Install nextcloud client flatpak
  become: yes
  become_user: "{{ desktop_user.username }}"
  flatpak:
    name: "com.nextcloud.desktopclient.nextcloud"
    state: present
    method: user

- name: Create the autostart folder
  become: yes
  become_user: "{{ desktop_user.username }}"
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/autostart"
    state: directory
    owner: "{{ desktop_user.username }}"

- name: Setup autostart for nextcloud flatpak
  become: yes
  become_user: "{{ desktop_user.username }}"
  file:
    src: "{{ lookup('env', 'HOME') }}/.local/share/flatpak/exports/share/applications/com.nextcloud.desktopclient.nextcloud.desktop"
    dest: "{{ lookup('env', 'HOME') }}/.config/autostart/com.nextcloud.desktopclient.nextcloud.desktop"
    state: link
