---
roles:
  - name: cimon-io.asdf
    version: v1.1.0

collections:
  - name: community.general
    version: 8.4.0

  - name: kubernetes.core
    version: 2.4.0

  - name: community.docker
    version: 3.4.9
