---
roles:
  - name: cimon-io.asdf
    version: v1.1.0

collections:
  - name: community.general
    version: 6.4.0

  - name: kubernetes.core
    version: 2.4.0

  - name: containers.podman
    version: 1.10.1
