---
# tasks file for user
- name: Create user-named group per user
  group:
    name: "{{ item.username }}"
    state: present
  with_items: "{{ users }}"

- name: Create users
  user:
    name: "{{ item.username }}"
    comment: "{{ item.get('comment', '') }}"
    groups: "{{ item['groups'] | default(item.username) }}"
    append: yes
    state: present
  with_items: "{{ users }}"

- name: Install sudo
  package:
    name: sudo
    state: present
