---
# tasks file for user
- name: Create user-named group per user
  group:
    name: "{{ desktop_user.username }}"
    state: present

- name: Create user
  user:
    name: "{{ desktop_user.username }}"
    comment: "{{ desktop_user.get('comment', '') }}"
    groups: "{{ desktop_user['groups'] | default(desktop_user.username) }}"
    append: yes
    state: present

- name: Install sudo
  package:
    name: sudo
    state: present
