---
# tasks file for user
- name: Create user-named group per user
  group:
    name: "{{ item.key }}"
    state: present
  with_dict: "{{ users }}"

- name: Create users
  user:
    name: "{{ item.key }}"
    comment: "{{ item.get('comment', '') }}"
    groups: "{{ item['groups'] | default(item.key) }}"
    append: yes
    state: present
  with_dict: "{{ users }}"

