---

- name: Setup helm package repository
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

- name: Install apt https transport
  package:
    name: apt-transport-https
    state: present

- name: Add apt repository for helm
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present

- name: Install helm
  package:
    name: helm
    state: present

- name: Install chart repository for nextcloud
  community.kubernetes.helm_repository:
    name: nextcloud
    repo_url: https://nextcloud.github.io/helm/

- name: Install nextcloud helm chart
  community.kubernetes.helm:
    release_name: mimir-nextcloud
    chart_ref: nextcloud/nextcloud
    release_namespace: "{{ k8s_nextcloud_namespace }}"
    create_namespace: true
    values: "{{ lookup('template', 'values.yaml') | from_yaml }}"
