---

- name: Setup helm package repository
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

- name: Install apt https transport
  package:
    name: apt-transport-https
    state: present

- name: Add apt repository for helm
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present

- name: Install helm
  package:
    name: helm
    state: present

- name: Install chart repository for nextcloud
  kubernetes.core.helm_repository:
    name: nextcloud
    repo_url: https://nextcloud.github.io/helm/

- name: Install nextcloud helm chart
  kubernetes.core.helm:
    release_name: mimir-nextcloud
    chart_ref: nextcloud/nextcloud
    release_namespace: "{{ k8s_nextcloud_namespace }}"
    create_namespace: true
    values: "{{ lookup('template', 'values.yaml') | from_yaml }}"

- name: Patch ingress resource to include the path
  command:
    cmd: |
      {{ k8s_kubectl }} patch -n "{{ k8s_nextcloud_namespace }}" ingress/mimir-nextcloud --type=json -p '[{"op": "replace", "path": "/spec/rules/0/http/paths/0/path", "value": "/nextcloud(/|$)(.*)"}]'

- name: Install a cronjob for webcron
  vars:
    ansible_python_interpreter: "{{ k8s_virtualenv }}/bin/python"
  kubernetes.core.k8s:
    api_version: batch/v1
    kind: CronJob
    definition:
      metadata:
        name: mimir-nextcloud-webcron
        namespace: "{{ k8s_nextcloud_namespace }}"
      spec:
        successfulJobsHistoryLimit: 0
        failedJobsHistoryLimit: 1
        schedule: "0 */12 * * *"
        jobTemplate:
          spec:
            template:
              spec:
                containers:
                - name: webcron
                  image: nextcloud:21.0.3-apache
                  imagePullPolicy: IfNotPresent
                  command: [ "curl" ]
                  args:
                  - "--fail"
                  - "-L"
                  - "https://{{ k8s_ingress_hostname }}/nextcloud/cron.php"
                restartPolicy: OnFailure

- name: Create a configmap for cronjob news updater
  kubernetes.core.k8s:
    api_version: v1
    kind: ConfigMap
    definition:
      metadata:
        name: mimir-nextcloud-news-updater
        namespace: "{{ k8s_nextcloud_namespace }}"
      data:
        config.ini: |
          [updater]
          user = {{ lookup('community.general.passwordstore', 'server/mimir.niflheim.cc.nextcloud.news.password subkey=username') }}
          password = {{ lookup('community.general.passwordstore', 'server/mimir.niflheim.cc.nextcloud.news.password') }}
          threads = 1
          interval = 900
          logleve = error
          url = https://your-nextcloud.com/
          apilevel = v15
          mode = singlerun

- name: Install a cronjob for news
  vars:
    ansible_python_interpreter: "{{ k8s_virtualenv }}/bin/python"
  kubernetes.core.k8s:
    api_version: batch/v1
    kind: CronJob
    definition:
      metadata:
        name: mimir-nextcloud-news-updater
        namespace: "{{ k8s_nextcloud_namespace }}"
      spec:
        schedule: "0 */12 * * *"
        jobTemplate:
          spec:
            template:
              spec:
                containers:
                - name: news-updater
                  image: ghcr.io/bergmannf/nextcloud-news-updater-image:main
                  imagePullPolicy: IfNotPresent
                  args:
                  - "--config"
                  - "/var/updater/config.ini"
                  volumeMounts:
                    - name: configuration
                      mountPath: /var/updater
                restartPolicy: Never
                volumes:
                  - name: configuration
                    configMap:
                      name: news-updater
