---
# tasks file for roles/server/adblock

- name: Setup the mountpoints on the host
  file:
    name: "{{ item }}"
    state: directory
    owner: "root"
    group: "root"
  with_items:
    - /media/adguard/work
    - /media/adguard/conf

- name: Run adblock container
  containers.podman.podman_container:
    name: adguardhome
    image: docker.io/adguard/adguardhome:v0.107.43
    state: started
    mount:
      - "type=bind,source=/media/adguard/work,destination=/opt/adguardhome/work"
      - "type=bind,source=/media/adguard/conf,destination=/opt/adguardhome/conf"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "784:784/udp"
      - "853:853/tcp"
      - "853:853/udp"
      - "3000:3000/tcp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
      - "8853:8853/udp"
    generate_systemd:
      new: true
      restart: on-failure
      path: /usr/lib/systemd/system/

- name: Enable the new systemd-service
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    daemon_reload: true
    name: container-adguardhome
