---
# tasks file for wallpaper
- name: Install feh to display the wallpaper
  package:
    name: feh
    state: present

- name: Create wallpaper folder
  file:
    state: directory
    mode: 0755
    dest: "/usr/share/wallpapers/"

- name: Download wallpaper
  get_url:
    url: "{{ wallpaper_url }}"
    dest: "/usr/share/wallpapers/{{ wallpaper }}"
    checksum: "sha1:39ade81328e42c1ef07f74f144fb92d81c712483"
