---
- name: Install steam and steam-devices packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - steam
    - steam-devices

# This is a workaround, as the steam-devices udev-rule for the steam controller must be loaded
# before the 71-seat.rules
- name: Move the steam-devices rules file
  command: cp /lib/udev/rules.d/99-steam-controller-perms.rules /lib/udev/rules.d/69-steam-controller-perms.rules
