---
- name: Include variables for SUSE
  include_vars: "vars/Suse.yml"

- name: Install ssl dependency
  zypper:
    name: python-pyOpenSSL
    state: present

- name: Download scala rpm
  get_url:
    url: "{{ scala_url }}"
    dest: /tmp/scala.rpm

- name: Install scala rpm
  zypper:
    name: "/tmp/scala.rpm"
    state: present
