---
- name: Setup repositories
  include_tasks: "{{ item }}"
  with_first_found:
    - "repositories_{{ ansible_os_family }}.yml"

- name: Install visual studio code
  package:
    name: code
    state: present

- name: Copy personal configuration
  become: yes
  become_user: "{{ item.username }}"
  template:
    src: "settings.json"
    dest: "~/.config/Code/User/settings.json"
  with_items: "{{ users }}"

- name: Install extensions
  become: yes
  become_user: "{{ item.0.username }}"
  command: /usr/bin/code --install-extension "{{ item.1 }}"
  with_subelements:
    - "{{ users }}"
    - vscodeextensions
  