---
- name: Setup repositories
  include_tasks: "{{ item }}"
  with_first_found:
    - "repositories_{{ ansible_os_family }}.yml"

- name: Install visual studio code
  package:
    name: code
    state: present

- name: Create configuration directory
  become: yes
  become_user: "{{ item.username }}"
  file:
    path: "~/.config/Code/User/"
    state: directory
  with_items: "{{ users }}"

- name: Copy personal configuration
  become: yes
  become_user: "{{ item.username }}"
  template:
    src: "settings.json"
    dest: "~/.config/Code/User/settings.json"
  with_items: "{{ users }}"

- name: Install extensions
  become: yes
  become_user: "{{ item.0.username }}"
  command: /usr/bin/code --install-extension "{{ item.1 }}"
  with_subelements:
    - "{{ users }}"
    - vscodeextensions
    
- name: Set as default editor
  become: yes
  become_user: "{{ item.username }}"
  lineinfile:
    path: "~/.zshenv"
    regexp: "^export EDITOR="
    line: "export EDITOR='code -r -w'"
  with_items: "{{ users }}"
  
- name: Create font rendering work around for fontconfig 2.8.*
  template:
    mode: 0644
    src: 99-vscode.conf
    dest: /etc/fonts/conf.d/99-vscode.conf
  when: ansible_os_family == "Debian"  