---
- name: Load Windows variables
  include_vars: "windows.yml"

- name: Install vscode
  win_chocolatey:
    name: vscode
    state: latest

- name: Create configuration directory
  win_file:
    path: "{{ code_config_path }}"
    state: directory

- name: Copy personal configuration
  win_template:
    src: "settings.json"
    dest: "{{ code_config_path }}settings.json"

- name: Install required extensions
  win_command: "powershell.exe {{ code_path }} --install-extension {{ item }}"
  with_items: "{{ extensions }}"

- name: Install extensions
  win_command: "powershell.exe {{ code_path }} --install-extension {{ item.1 }}"
  with_items: "{{ desktop_user.vscodeextensions }}"
