---
- name: Overwrite variables
  include_vars: windows.yml
  when: ansible_os_family == "Windows"

- name: Setup repositories
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
      - "repositories_{{ ansible_os_family }}.yml"
      skip: true

- name: Install visual studio code
  include_tasks: "{{ item }}"
  with_first_found:
    - "install_{{ ansible_os_family }}.yml"

- name: Configure visual studio code (Windows)
  include_tasks: "configure_{{ ansible_os_family }}.yml"
  when: {{ ansible_os_family }} == "Windows"

- name: Configure visual studio code (Linux)
  include_tasks: "configure_linux.yml"
  when: {{ ansible_os_family }} != "Windows"