---
- name: Install https transport
  package:
    name: apt-transport-https
    state: present

- name: Add microsoft key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add microsoft repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode
    update_cache: yes
