---
nextcloud:
  host: "{{ k8s_ingress_hostname }}"
  password: '{{ k8s_nextcloud_password }}'
  extraEnv:
    # https://serverfault.com/questions/998024/nextcloud-behind-ngnix-reverse-proxy-in-a-subdir-url
    - name: OVERWRITEWEBROOT
      value: "/nextcloud"
    - name: OVERWRITEHOST
      value: "{{ k8s_ingress_hostname }}"
    - name: OVERWRITEPROTOCOL
      value: "https"
mariadb:
  enabled: true
  db:
    password: '{{ k8s_nextcloud_mariadb_password }}'
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  tls:
    - hosts:
        - "{{ k8s_ingress_hostname }}"
      secretName: nextcloud-web-tls-cert
persistence:
  enabled: true
  storageClass: "{{ k8s_storageclass_name }}"
  size: "{{ k8s_nextcloud_storage_size }}"
