---
image:
  tag: 25.0.1-apache
nextcloud:
  host: "{{ k8s_ingress_hostname }}"
  password: '{{ k8s_nextcloud_password }}'
  extraEnv:
    # https://serverfault.com/questions/998024/nextcloud-behind-ngnix-reverse-proxy-in-a-subdir-url
    - name: OVERWRITEWEBROOT
      value: "/nextcloud"
    - name: OVERWRITEHOST
      value: "{{ k8s_ingress_hostname }}"
    - name: OVERWRITEPROTOCOL
      value: "https"
mariadb:
  enabled: true
  auth:
    database: nextcloud
    password: '{{ k8s_nextcloud_mariadb_password }}'
    username: nextcloud
    rootPassword: '{{ k8s_nextcloud_mariadb_password }}'
  primary:
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 8Gi
  volumePermissions:
    enabled: true
internalDatabase:
  enabled: false
ingress:
  enabled: true
  className: "public"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    nginx.ingress.kubernetes.io/proxy-body-size: "256m"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
  tls:
    - hosts:
        - "{{ k8s_ingress_hostname }}"
      secretName: nextcloud-web-tls-cert
persistence:
  enabled: true
  storageClass: "{{ k8s_storageclass_name }}"
  size: "{{ k8s_nextcloud_storage_size }}"
cronjob:
  enabled: true
