---
# Do this all in one go, because setting group permissions can take forever
- name: Install required languages using asdf
  include_role:
    name: cimon-io.asdf
  vars:
    asdf_plugins:
      - name: "golang"
        versions:
          - latest
        global: latest
      - name: "terraform"
        versions:
          - latest
        global: latest
      - name: "terraform-ls"
        versions:
          - latest
        global: latest
      - name: "nodejs"
        versions:
          - latest
        global: latest
      - name: "kind"
        versions:
          - latest
        global: latest
    asdf_user: "{{ desktop_user.username }}"

- name: Ensure asdf is loaded in shell-startup
  become: true
  become_user: "{{ desktop_user.username }}"
  blockinfile:
    dest: ~/.zshrc
    block: |
      if [ -f ~/.asdf/asdf.sh ]; then
        source "$HOME/.asdf/asdf.sh"
      fi
    insertafter: "# ZSHRC FOOTER"

- name: Setup path
  include_role:
    name: env
  vars:
    KEY: PATH
    VALUE: "${HOME}/.asdf/shims:${HOME}/.asdf/bin:${PATH}"
