---
- name: Install starship
  package:
    name: starship
    state: present

- name: Use starship theme
  become: yes
  become_user: "{{ desktop_user.username }}"
  lineinfile:
    dest: "~/.zshrc"
    line: 'eval "$(starship init zsh)"'
