---
# tasks file for zsh
- name: Install zsh package
  package:
    name:
      - zsh
      - zsh-syntax-highlighting
    state: present

- name: Set as default shell
  user:
    name: "{{ desktop_user.username }}"
    shell: /bin/zsh

- name: Create zsh directories
  become: true
  become_user: "{{ desktop_user.username }}"
  file:
    state: directory
    mode: 0755
    owner: "{{ desktop_user.username }}"
    dest: "{{ item }}"
  with_items:
    - "~/.zfunctions"
    - "~/.zsh"

- name: Install zsh configuration
  become: true
  become_user: "{{ desktop_user.username }}"
  template:
    mode: 0644
    src: zshrc.j2
    owner: "{{ desktop_user.username }}"
    dest: "~/.zshrc"

- name: Install ssh-agent.zsh
  become: true
  become_user: "{{ desktop_user.username }}"
  template:
    mode: 0644
    src: ssh-agent.zsh
    owner: "{{ desktop_user.username }}"
    dest: "~/.zsh/ssh-agent.zsh"

- name: Copy async library
  become: true
  become_user: "{{ desktop_user.username }}"
  copy:
    src: "{{ role_path }}/templates/async.zsh"
    dest: "~/.zfunctions/async"
    owner: "{{ desktop_user.username }}"

- name: Install zsh theme
  include_tasks: install_theme.yml

- name: Copy aliases
  become: true
  become_user: "{{ desktop_user.username }}"
  copy:
    src: "{{ role_path }}/templates/{{ item }}"
    dest: "~/.{{ item }}"
    owner: "{{ desktop_user.username }}"
  with_items:
    - aliases
    - aliases.zsh

- name: Add additional zsh-completions
  become: true
  become_user: "{{ desktop_user.username }}"
  git:
    repo: https://github.com/zsh-users/zsh-completions.git
    dest: "~/.zcompletions"
    update: yes

- name: Clone zsh-autosuggestions
  become: true
  become_user: "{{ desktop_user.username }}"
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.zsh/zsh-autosuggestions
    update: yes

- name: Install zsh-autosuggestions
  become: true
  become_user: "{{ desktop_user.username }}"
  lineinfile:
    dest: ~/.zshrc
    line: "source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh"

- name: Install zsh-syntaxhighlighting
  become: true
  become_user: "{{ desktop_user.username }}"
  lineinfile:
    dest: ~/.zshrc
    line: "source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
