---
# tasks file for zsh
- name: Install zsh package
  package:
    name: zsh
    state: present

- name: Users
  debug: "{{ item.key }}"
  with_dict: "{{ users }}"

- name: Set as default shell
  user:
    name: "{{ item.key }}"
    shell: /bin/zsh
  with_dict: "{{ users }}"

- name: Install zsh configuration
  become: true
  become_user: "{{ item.key }}"
  template:
    mode: 0644
    src: zshrc.j2
    owner: "{{ item.key }}"
    dest: "{{ ansible_env.HOME }}/.zshrc"
  with_dict: "{{ users }}"

- name: Create zfunction directory
  become: true
  become_user: "{{ item.key }}"
  file:
    state: directory
    mode: 0755
    owner: "{{ item.key }}"
    dest: "{{ ansible_env.HOME }}/.zfunctions"
  with_dict: "{{ users }}"

- name: Copy async library
  copy:
    src: "{{ role_path }}/templates/async.zsh"
    dest: "{{ ansible_env.HOME }}/.zfunctions/async"
    owner: "{{ item.key }}"
  with_dict: "{{ users }}"

- name: Copy pure theme
  become: true
  become_user: "{{ item.key }}"
  copy:
    src: "{{ role_path }}/templates/pure.zsh"
    dest: "/{{ ansible_env.HOME }}/.zfunctions/prompt_pure_setup"
    owner: "{{ item.key }}"
  with_dict: "{{ users }}"
