---
# tasks file for zsh
- name: Install zsh package
  package:
    name: zsh
    state: present

- name: Set as default shell
  user:
    name: "{{ item.key }}"
    shell: /bin/zsh
  with_dict: "{{ users }}"

- name: Create zfunction directory
  become: true
  become_user: "{{ item.key }}"
  file:
    state: directory
    mode: 0755
    owner: "{{ item.key }}"
    dest: "~/.zfunctions"
  with_dict: "{{ users }}"

- name: Install zsh configuration
  become: true
  become_user: "{{ item.key }}"
  template:
    mode: 0644
    src: zshrc.j2
    owner: "{{ item.key }}"
    dest: "~/.zshrc"
  with_dict: "{{ users }}"

- name: Install zprofile configuration
  become: true
  become_user: "{{ item.key }}"
  template:
    mode: 0644
    src: zprofile.j2
    owner: "{{ item.key }}"
    dest: "~/.zprofile"
  with_dict: "{{ users }}"

- name: Copy async library
  become: true
  become_user: "{{ item.key }}"
  copy:
    src: "{{ role_path }}/templates/async.zsh"
    dest: "~/.zfunctions/async"
    owner: "{{ item.key }}"
  with_dict: "{{ users }}"

- name: Copy pure theme
  become: true
  become_user: "{{ item.key }}"
  copy:
    src: "{{ role_path }}/templates/pure.zsh"
    dest: "~/.zfunctions/prompt_pure_setup"
    owner: "{{ item.key }}"
  with_dict: "{{ users }}"

- name: Copy aliases
  become: true
  become_user: "{{ item.key }}"
  copy:
    src: "{{ role_path }}/templates/aliases"
    dest: "~/.aliases"
    owner: "{{ item.key }}"
  with_dict: "{{ users }}"

- name: Add additional zsh-completions
  become: true
  become_user: "{{ item.key }}"
  git:
    repo: https://github.com/zsh-users/zsh-completions.git
    dest: "~/.zcompletions"
    update: yes
  with_dict: "{{ users }}"
