import = [
    "~/.config/alacritty/themes/themes/challenger_deep.toml"
]

[font]
size = 13.0

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "E"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"
