---

- name: Create a backup cronjob for the passed pvc
  vars:
    ansible_python_interpreter: "{{ k8s_virtualenv }}/bin/python"
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', item) }}"
  loop:
    - 01-secret.yaml
    - 02-cronjob.yaml
