---
# tasks file for pass
- name: Load variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_os_family }}.yml"

- name: Install pass packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: Install passmenu script
  become: yes
  become_user: root
  copy:
    src: "{{ role_path }}/templates/passmenu"
    dest: "/usr/bin/passmenu"
    owner: "root"
    mode: "u+rwx,g+rx,o+rx"
