---

- name: Setup docker repository
  yum_repository:
    name: docker
    description: docker repository
    baseurl: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/$releasever/$basearch/stable"
    gpgkey: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
  when: ansible_distribution != "AlmaLinux"

- name: Setup docker repository
  yum_repository:
    name: docker
    description: docker repository
    baseurl: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
    gpgkey: "https://download.docker.com/linux/centos/gpg"
  when: ansible_distribution in ["AlmaLinux", "CentOS", "RockyLinux"]

- name: Install docker as a container runtime
  package:
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Enable docker to start on boot
  systemd_service:
    name: docker
    enabled: yes
    state: started
