---
- name: Install dependencies to manage repositories
  package:
    name: "{{ item }}"
    state: present
  with_items: ["gnupg2", "apt-transport-https"]

- name: Add sbt bintray key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 2EE0EA64E40A89B84B2DF73499E82A75642AC823

- name: Add sbt bintray repository
  apt_repository:
    repo: deb "https://dl.bintray.com/sbt/debian" /
    state: present

- name: Update apt cache
  apt:
    update_cache: yes
