---
# tasks file for sbt
- name: Run distribution tasks
  include: "{{ ansible_os_family }}.yml"

- name: Install sbt
  package: 
    name: sbt
    state: present

- name: Create plugin directory
  become: yes
  become_user: "{{ desktop_user.username }}"
  file:
    dest: "~/.sbt/{{ sbt_version }}/plugins/"
    owner: "{{ desktop_user.username }}"
    group: "{{ desktop_user.username }}"
    mode: 0755
    state: directory

- name: Create plugins file
  become: yes
  become_user: "{{ desktop_user.username }}"
  copy:
    content: ""
    dest: "~/.sbt/{{ sbt_version }}/plugins/plugins.sbt"
    owner: "{{ desktop_user.username }}"
    group: "{{ desktop_user.username }}"
    force: no
    mode: 0644

- name: Global ensime plugin
  become: yes
  become_user: "{{ desktop_user.username }}"
  lineinfile:
    dest: "~/.sbt/{{ sbt_version }}/plugins/plugins.sbt"
    regexp: 'addSbtPlugin\("org.ensime" % "sbt-ensime" % ".*"\)'
    line: addSbtPlugin("org.ensime" % "sbt-ensime" % "{{ ensime_version }}")
    state: present
