---

- name: Install the Gnome group
  dnf:
    name: 
      - "@Fedora Workstation"
      - dconf-editor
      - gnome-shell-extension-pomodoro
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-auto-move-windows
      - gnome-shell-extension-forge
      # Needed by the pop-shell extension
      - pinentry-gnome3
      - firefox
      - mozilla-ublock-origin
      - python3-psutil
    state: present
