---

- name: Install the Gnome group
  package:
    name: 
      - dconf-editor
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-forge
      # Needed by the pop-shell extension
      - pinentry
      - firefox
      - firefox-ublock-origin
      - python-psutil
    state: present
