---

- name: Install the Gnome group
  dnf:
    name: 
      - "@GNOME Desktop Environment"
      - dconf-editor
      - gnome-shell-extension-pomodoro
      - pinentry-gnome3
      - firefox
      - mozilla-ublock-origin
    state: present
