---
# tasks file for git
- name: Install git package
  package:
    name: git
    state: present
  with_items:
    - git
    - ssh-askpass
    - ssh-askpass-gnome

- name: Configure name
  become: yes
  become_user: "{{ item.username }}"
  git_config:
    name: user.name
    value: "{{ item.fullname }}"
    scope: global
  with_items: "{{ users }}"

- name: Create email
  become: yes
  become_user: "{{ item.username }}"
  git_config:
    name: user.email
    value: "{{ item.email }}"
    scope: global
  with_items: "{{ users }}"
