---
# tasks file for git
- name: Install git package
  package:
    name: git
    state: present
  with_items:
    - git
    - ssh-askpass
    - ssh-askpass-gnome

- name: Configure name
  become: yes
  become_user: "{{ desktop_user.username }}"
  git_config:
    name: user.name
    value: "{{ desktop_user.fullname }}"
    scope: global

- name: Create email
  become: yes
  become_user: "{{ desktop_user.username }}"
  git_config:
    name: user.email
    value: "{{ desktop_user.email }}"
    scope: global
