---
# tasks file for git
- name: Install git package
  package:
    name: git
    state: present

- name: Configure name
  git_config:
    name: user.name
    value: "{{ item.fullname }}"
    scope: global
  with_items: "{{ users }}"

- name: Create email
  git_config:
    name: user.email
    value: "{{ item.e.email }}"
    scope: global
  with_items: "{{ users }}"
