- name: Clone .emacs.d
  become: yes
  become_user: "{{ desktop_user.username }}"
  git:
    repo: https://github.com/hlissner/doom-emacs
    dest: ~/.config/emacs/
    update: yes
    depth: 1
    version: master
  when: emacsd.stat.exists == False

- name: Make sure $HOME/.doom.d exists
  become: yes
  become_user: "{{ desktop_user.username }}"
  file:
    path: $HOME/.config/doom/
    state: directory
    owner: "{{ desktop_user.username }}"

- name: Copy doom configuration files
  become: yes
  become_user: "{{ desktop_user.username }}"
  template:
    src: "doom-{{ item }}.el"
    dest: "~/.config/doom/{{ item }}.el"
    owner: "{{ desktop_user.username }}"
    mode: 0644
  with_items:
    - init
    - config
    - packages

- name: Add .emacs.d/bin to PATH
  become: yes
  become_user: "{{ desktop_user.username }}"
  lineinfile:
    dest: "~/.zshenv"
    line: 'PATH="$HOME/.config/emacs/bin:$PATH"'
    insertafter: "# PATH config:"
