---
# tasks file for emacs
- name: Install emacs
  include: "{{ ansible_os_family }}.yml"

- name: Spacemacs repository checkout for .emacs.d
  include: emacsd.yml user="{{ item }}"
  with_items: "{{ users }}"

- name: Spacemacs configuration file
  become: yes
  become_user: "{{ item.username }}"
  template:
    src: spacemacs.j2
    dest: ~/.spacemacs
    owner: "{{ item.username }}"
    mode: 0644
  with_items: "{{ users }}"
