---
# tasks file for emacs
- name: Install emacs
  include: "{{ ansible_os_family }}.yml"

- name: Spacemacs repository checkout for .emacs.d
  include: emacsd.yml user="{{ desktop_user }}"

- name: Spacemacs configuration file
  become: yes
  become_user: "{{ desktop_user.username }}"
  template:
    src: spacemacs.j2
    dest: ~/.spacemacs
    owner: "{{ desktop_user.username }}"
    mode: 0644
