---
# tasks file for emacs
- name: Install emacs
  include: "{{ ansible_os_family }}.yml"

- name: Spacemacs repository checkout for .emacs.d
  include: emacsd.yml user="{{ desktop_user }}"

- name: Install spacemacs
  include_tasks: install_spacemacs.yml
  when: emacs_distribution == "spacemacs"

- name: Install doom
  include_tasks: install_doom.yml
  when: emacs_distribution == "doom"
