---
# tasks file for emacs
- name: Install emacs
  include: "{{ ansible_os_family }}.yml"

- name: Spacemacs repository checkout for .emacs.d
  include: emacsd.yml user="{{ desktop_user }}"

- name: Install spacemacs
  include_tasks: install_spacemacs.yml
  when: emacs_distribution == "spacemacs"

- name: Install doom
  include_tasks: install_doom.yml
  when: emacs_distribution == "doom"

- name: Ensure the bin directory exists
  become: yes
  become_user: "{{ desktop_user.username }}"
  ansible.builtin.file:
    path: "~/bin"
    state: directory
    mode: "0755"
    owner: "{{ desktop_user.username }}"

- name: Copy the update_emacs_env script
  become: yes
  become_user: "{{ desktop_user.username }}"
  copy:
    src: update_emacs_env
    dest: "~/bin/update_emacs_env"
    owner: "{{ desktop_user.username }}"
    mode: "0755"
