---

- name: Install nodenv (user only)
  become: yes
  become_user: "{{ user.username }}"
  git:
    dest: "~/.nodenv"
    repo: https://github.com/nodenv/nodenv.git

- name: Check nodenv-plugins directory exists.
  become: yes
  become_user: "{{ user.username }}"
  stat:
    path: "~/.nodenv/plugins"
  register: file_details

- debug:
    var: file_details

- name: Create nodeenv-plugins directory
  become: yes
  become_user: "{{ user.username }}"
  file:
    path: "~/.nodenv/plugins"
    state: directory
    owner: "{{ user.username }}"
  when: not file_details.stat.exists

- name: Install node-build
  become: yes
  become_user: "{{ user.username }}"
  git:
    dest: "~/.nodenv/plugins/node-build/"
    repo: https://github.com/nodenv/node-build.git