---
- name: Install golang via asdf
  include_role:
    name: cimon-io.asdf
  vars:
    asdf_plugins:
      - name: "nodejs"
        versions:
          - latest
        global: latest

- name: Install indium package for emacs
  become: yes
  become_user: "{{ desktop_user.username }}"
  shell: source ~/.zshrc; npm install -g indium
  args:
    executable: "{{ ZSH_BIN }}"
