---

- name: Check installed plugins
  become: yes
  become_user: "{{ desktop_user.username }}"
  shell: source ~/.zshrc; asdf plugin list
  register: asdf_plugins
  args:
    executable: "{{ ZSH_BIN }}"

- name: Install node plugin for asdf
  become: yes
  become_user: "{{ desktop_user.username }}"
  shell: source ~/.zshrc; asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  args:
    executable: "{{ ZSH_BIN }}"
  when: '"nodejs" not in asdf_plugins.stdout'
