---

- name: Clone nodenv projects
  include_tasks: git.yml
  vars:
    user: "{{ desktop_user }}"

- name: Add nodenv to PATH
  become: yes
  become_user: "{{ desktop_user.username }}"
  lineinfile:
    dest: "~/.zshenv"
    line: 'PATH="$HOME/.nodenv/bin:$PATH"'
    insertafter: "# PATH config:"

- name: Initialize nodenv
  become: yes
  become_user: "{{ desktop_user.username }}"
  lineinfile:
    dest: "~/.zshrc"
    line: 'eval "$(nodenv init -)"'
