---

- name: Clone nodenv projects
  include_tasks: git.yml
  vars:
    user: "{{ item }}"
  with_items: "{{ users }}"

- name: Add nodenv to PATH
  become: yes
  become_user: "{{ item.username }}"
  lineinfile:
    dest: "~/.zshenv"
    line: 'PATH="$HOME/.nodenv/bin:$PATH"'
    insertafter: "# PATH config:"
  with_items: "{{ users }}"

- name: Initialize nodenv
  become: yes
  become_user: "{{ item.username }}"
  lineinfile:
    dest: "~/.zshrc"
    line: 'eval "$(nodenv init -)"'
  with_items: "{{ users }}"