---
- name: Download the rustup installer
  get_url:
    dest: /tmp/rustup.sh
    url:  https://sh.rustup.rs
    mode: 0755

- name: Install the rustup toolchain for the user
  become: yes
  become_user: "{{ desktop_user.username }}"
  command: /tmp/rustup.sh -y --no-modify-path

- name: Add .cargo/bin to PATH
  include_role:
    name: env
  vars:
    KEY: PATH
    VALUE: "${PATH}:${HOME}/.cargo/bin"

- name: Install rust completions
  become: yes
  become_user: "{{ desktop_user.username }}"
  shell: ~/.cargo/bin/rustup completions zsh > ~/.zfunctions/_rustup

- name: Install toolchain
  become: yes
  become_user: "{{ desktop_user.username }}"
  command: ~/.cargo/bin/rustup install stable
  args:
    creates: ~/.rustup

- name: Set default toolchain
  become: yes
  become_user: "{{ desktop_user.username }}"
  command: "~/.cargo/bin/rustup default stable-x86_64-unknown-linux-gnu"
  args:
    creates: "~/.rustup/toolchains"

- name: Install dev components
  become: yes
  become_user: "{{ desktop_user.username }}"
  command: "~/.cargo/bin/rustup component add {{ item }}"
  args:
    creates: "~/.cargo/bin/{{ item }}"
  with_items:
    - rust-analysis
    - rust-src
    - rustfmt
    - rust-analyzer
