---

- name: Check installed plugins
  become: yes
  become_user: "{{ desktop_user.username }}"
  shell: source ~/.zshrc; asdf plugin list || echo ""
  register: asdf_plugins
  args:
    executable: "{{ ZSH_BIN }}"

- name: Install kind plugin for asdf
  become: yes
  become_user: "{{ desktop_user.username }}"
  shell: source ~/.zshrc; asdf plugin-add kind
  args:
    executable: "{{ ZSH_BIN }}"
  when: '"kind" not in asdf_plugins.stdout'

- name: Install latest version for kind
  become: yes
  become_user: "{{ desktop_user.username }}"
  shell: source ~/.zshrc; asdf install kind "{{ kind_version }}"; asdf global kind "{{ kind_version }}"
  args:
    executable: "{{ ZSH_BIN }}"
