- name: Install i3wm packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - dex
    - compton
    - i3
    - rofi
    - redshift
    - suckless-tools
    - x11-xserver-utils
    - gawk
    - i3blocks
    - pasystray
