---
# tasks file for i3wm
- include: "{{ ansible_os_family }}.yml"

# Use some hackery to get valid JSON output:
# print variable 't' in AWK that is *not* set on the first iteration.
# For any iteration thereafter it inserts the required ',' except for the last
# iteration.
- name: Determine monitors
  shell: |
    xrandr |\
    grep --extended-regexp "\bconnected" |\
    gawk 'BEGIN { print "{\"Monitors\": {" } { print t "\"" $1 "\": {\"Name\": \"" $1 "\","}; match($0, /[0-9]{2,}x[0-9]+/, ary) { print "\"Resolution\": \"" ary[0] "\"}" } { t="," } END { print "}}"}'
  register: monitors

# Turn the 
- name: Set monitors fact
  set_fact:
    monitors: "{{ monitors.stdout | from_json }}"

- name: Create i3-config directory
  become: true
  become_user: "{{ item.username }}"
  file:
    state: directory
    mode: 0755
    owner: "{{ item.username }}"
    dest: "~/.i3/"
  with_items: "{{ users }}"

- name: Debug monitors variable
  debug:
    var: monitors

- name: Copy configuration for i3
  become: true
  become_user: "{{ item.username }}"
  template:
    src: i3config.j2
    dest: "~/.i3/config"
    owner: "{{ item.username }}"
    mode: 0644
  with_items: "{{ users }}"
  notify: Set wallpaper in config

- name: Copy i3blocks configuration
  become: true
  become_user: "{{ item.username }}"
  template:
    src: i3blocks.j2
    dest: "~/.i3/i3blocks.conf"
    owner: "{{ item.username }}"
    mode: 0744
  with_items: "{{ users }}"
