---
# tasks file for i3wm
- include: "{{ ansible_os_family }}.yml"

- name: Load variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

# Use some hackery to get valid JSON output:
# print variable 't' in AWK that is *not* set on the first iteration.
# For any iteration thereafter it inserts the required ',' except for the last
# iteration.
- name: Determine monitors
  shell: |
    xrandr |\
    grep --extended-regexp "\bconnected" |\
    gawk 'BEGIN { print "{\"Displays\": {" } { print t "\"" $1 "\": {\"Name\": \"" $1 "\","}; match($0, /[0-9]{2,}x[0-9]+/, ary) { print "\"Resolution\": \"" ary[0] "\"}" } { t="," } END { print "}}"}'
  register: monitors

# Turn the 
- name: Set monitors fact
  set_fact:
    monitors: "{{ monitors.stdout | from_json }}"

- name: Create i3-config directory
  become: true
  become_user: "{{ desktop_user.username }}"
  file:
    state: directory
    mode: 0755
    owner: "{{ desktop_user.username }}"
    dest: "~/.i3/"

- name: Copy configuration for i3
  become: true
  become_user: "{{ desktop_user.username }}"
  template:
    src: i3config.j2
    dest: "~/.i3/config"
    owner: "{{ desktop_user.username }}"
    mode: 0644
  notify: Set wallpaper in config

- name: Install bar
  include_tasks: install_bar.yml

- name: Copy i3lock wrapper script
  template:
    src: i3lock_wrapper.sh
    dest: "/usr/local/bin/i3lock_wrapper.sh"
    owner: root
    mode: 0777
    mode: 0777

- name: Ensure dunstrc config folder exists
  become: yes
  become_user: "{{ desktop_user.username }}"
  file:
    state: directory
    dest: "~/.config/dunst/"
    owner: "{{ desktop_user.username }}"
    mode: 0755

# This config prevents dunst from from capturing Ctrl+`
- name: Copy dunstrc
  become: yes
  become_user: "{{ desktop_user.username }}"
  template:
    src: dunstrc.j2
    dest: "~/.config/dunst/dunstrc"
    owner: "{{ desktop_user.username }}"
    mode: 0644

- name: Copy compton config
  become: yes
  become_user: "{{ desktop_user.username }}"
  template:
    src: compton.conf.j2
    dest: "~/.config/compton.conf"
    owner: "{{ desktop_user.username }}"
    mode: 0644

- name: Copy redshift config
  become: yes
  become_user: "{{ desktop_user.username }}"
  template:
    src: redshift.conf.j2
    dest: "~/.config/redshift.conf"
    owner: "{{ desktop_user.username }}"
    mode: 0644
