---
# tasks file for i3wm
- include: "{{ ansible_os_family }}.yml"

- name: Determine monitors
  shell: |
    xrandr |\
    grep --extended-regexp "\bconnected" |\
    gawk 'BEGIN { print "{\"Monitors\": {" } {print "\"" $1 "\": {\"Name\": \"" $1 "\","}; match($0, /[0-9]{2,}x[0-9]+/, ary) { print "\"Resolution\": \"" ary[0] "\"},"} END { print "}}"}'
  register: monitors

# Turn the 
- name: Set monitors fact
  set_fact:
    monitors: "{{ item }}"
  with_dict: "{{ ' '.join(monitors.stdout_lines) }}"

- name: Create i3-config directory
  become: true
  become_user: "{{ item.key }}"
  file:
    state: directory
    mode: 0755
    owner: "{{ item.key }}"
    dest: "~/.i3/"
  with_dict: "{{ users }}"

- name: Copy configuration for i3
  become: true
  become_user: "{{ item.key }}"
  template:
    src: i3config.j2
    dest: "~/.i3/config"
    owner: "{{ item.key }}"
    mode: 0644
  with_dict: "{{ users }}"
  notify: Set wallpaper in config

- name: Copy i3blocks configuration
  become: true
  become_user: "{{ item.key }}"
  template:
    src: i3blocks.j2
    dest: "~/.i3/i3blocks.conf"
    owner: "{{ item.key }}"
    mode: 0744
  with_dict: "{{ users }}"
