---
# tasks file for i3wm
- include: "{{ ansible_os_family }}.yml"

- name: Create i3-config directory
  become: true
  become_user: "{{ item.name }}"
  become_method: su
  file:
    state: directory
    mode: 0755
    owner: "{{ item.name }}"
    dest: "~/.i3/"
  with_dict: "{{ users }}"

- name: Determine monitors
  shell: |
    xrandr |\
    grep --extended-regexp "\bconnected" |\
    gawk 'BEGIN { print "Monitors:" } {print "  - " $1 ":\n      Name: " $1}; match($0, /[0-9]{2,}x[0-9]+/, ary) { print "      Resolution: " ary[0] }'
  register: monitors

- name: Copy configuration for i3
  template:
    src: i3config.j2
    dest: "~/.i3/config"
    owner: "{{ item.name }}"
    mode: 0644
  with_dict: "{{ users }}"
