- name: Install i3wm packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - compton
    - i3
    - i3status-rs
    - rofi
    - redshift
    - xorg-x11-server-utils
    - gawk
    # - i3blocks does not exist for centos without copr
    - pasystray
