- name: Install i3wm packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - dex-autostart
    - picom
    - i3
    - i3status-rs
    - rofi
    - redshift
    - xorg-x11-server-utils
    - gawk
    # - i3blocks does not exist for centos without copr
    - pasystray

- name: Add an alias for dex-autostart
  become: yes
  become_user: "{{ desktop_user.username }}"
  lineinfile:
    dest: ~/.aliases
    line: "alias dex='dex-autostart'"
