---
# tasks file for tmux
- name: Install tmux
  package:
    name: tmux
    state: present

- name: Set tmux_version fact
  shell: tmux -V | cut -d' ' -f2
  register: tmux_version

- name: Copy tmux theme
  become: yes
  become_user: "{{ item.username }}"
  copy:
    src: "{{ role_path }}/templates/tmux.theme.j2"
    owner: "{{ item.username }}"
    dest: "~/.tmux.theme"
    mode: 0644
  with_items: "{{ users }}"

- name: Copy tmux config
  become: yes
  become_user: "{{ item.username }}"
  template:
    src: "tmux.conf.j2"
    owner: "{{ item.username }}"
    dest: "~/.tmux.conf"
    mode: 0644
  with_items: "{{ users }}"
