---
# tasks file for tmux
- name: Install tmux
  package:
    name: tmux
    state: present

- name: Set tmux_version fact
  shell: tmux -V | cut -d' ' -f2
  register: tmux_version

- name: Install tmux tpm
  become: yes
  become_user: "{{ desktop_user.username }}"
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "~/.tmux/plugins/tpm"
    depth: 1

- name: Copy tmux theme
  become: yes
  become_user: "{{ desktop_user.username }}"
  copy:
    src: "{{ role_path }}/templates/{{ tmux_theme }}"
    owner: "{{ desktop_user.username }}"
    dest: "~/.tmux.theme"
    mode: 0644

- name: Copy tmux config
  become: yes
  become_user: "{{ desktop_user.username }}"
  template:
    src: "tmux.conf.j2"
    owner: "{{ desktop_user.username }}"
    dest: "~/.tmux.conf"
    mode: 0644

- name: Force install tpm plugins
  become: yes
  become_user: "{{ desktop_user.username }}"
  shell:
    cmd: "~/.tmux/plugins/tpm/tpm && ~/.tmux/plugins/tpm/bin/install_plugins"
