---
- name: Load variables for distribution
  include_vars: "{{ ansible_os_family }}.yml"

# tasks file for roles/virtualization
- name: Install required packages for virtualization
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - virt-manager
      - qemu-full
  when: ansible_os_family == "Archlinux"

- name: Install required packages for virtualization
  dnf:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - "@Virtualization"
  when: ansible_os_family == "RedHat"


- name: Add {{ desktop_user.username }} to libvirt group
  user:
    name: "{{ desktop_user.username }}"
    groups: "{{ libvirt_groups }}"
    append: yes
  become: yes

- name: Enable libvirtd
  service:
    name: libvirtd
    state: started
    enabled: yes
