---

- name: Install gstreamer plugins
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - gstreamer1.0-plugins-bad
    - gstreamer1.0-plugins-base
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-ugly