---

- name: Install the signing keys for rpmfusion
  rpm_key:
    state: present
    key: "{{ item }}"
  with_items:
    - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
    - https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020


- name: install the rpmfusion repo packages
  dnf:
    name: 
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
    state: present

# sudo dnf groupupdate multimedia --setop="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin
- name: Upgrade the codecs
  dnf:
    name: "@multimedia"
    install_weak_deps: no
    state: latest
    exclude: "PackageKit-gstreamer-plugin"

# sudo dnf groupupdate multimedia --setop="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin
- name: Upgrade the codecs
  dnf:
    name: "@sound-and-video"
    state: latest
