---

- name: Clone pyenv git repositories
  include_tasks: git.yml
  vars:
    user: "{{ item }}"
  with_items: "{{ users }}"

- name: Add pyenv to PATH
  become: yes
  become_user: "{{ item.username }}"
  lineinfile:
    dest: "~/.zshenv"
    line: 'PATH="$HOME/.pyenv/bin:$PATH"'
    insertafter: "# PATH config:"
  with_items: "{{ users }}"

- name: Initialize pyenv
  become: yes
  become_user: "{{ item.username }}"
  lineinfile:
    dest: "~/.zshrc"
    line: 'eval "$(pyenv init -)"'
  with_items: "{{ users }}"