---

- name: Install pipenv
  package:
    name: pipenv
    state: present

- name: Clone pyenv git repositories
  include_tasks: git.yml
  vars:
    user: "{{ desktop_user }}"

- name: Add pyenv to PATH
  become: yes
  become_user: "{{ desktop_user.username }}"
  lineinfile:
    dest: "~/.zshenv"
    line: 'PATH="$HOME/.pyenv/bin:$PATH"'
    insertafter: "# PATH config:"

- name: Initialize pyenv
  become: yes
  become_user: "{{ desktop_user.username }}"
  lineinfile:
    dest: "~/.zshrc"
    line: 'eval "$(pyenv init -)"'
