---

- name: Install pipenv
  package:
    name: poetry
    state: present
  when: ansible_os_family == "RedHat"

- name: Install pipenv
  pip:
    name: poetry
    state: present
    extra_args: --user
  when: ansible_os_family == "Debian"
