#!/usr/bin/env bash
# Kill all running containers.
alias dockerkillall='docker kill $(docker ps -q)'

# Delete all stopped containers.
alias dockercleanc='printf "\n>>> Deleting stopped containers\n\n" && docker rm $(docker ps -a -q)'

# Delete all untagged images.
alias dockercleani='printf "\n>>> Deleting untagged images\n\n" && docker rmi $(docker images -q -f dangling=true)'

# Delete all stopped containers and untagged images.
alias dockerclean='dockercleanc || true && dockercleani'

# Clean up no longer used volumes
alias dockercleanvol='printf "\n>>> Deleting unused volumes\n\n" && docker volume ls -qf dangling=true | xargs -r docker volume rm'

alias emacs="TERM=xterm-direct emacsclient -a '' -c -nw"

alias k='kubectl'

# Quick access emacsclient
alias e="TERM=xterm-direct emacsclient -a '' -c -nw"
alias ae="TERM=xterm-direct emacsclient -n"

alias fishenv="sed -E 's/([^=]+)=(.*)/set \1 \"\2\"/g'"

alias le='eza --long --all --icons=auto'

alias bat="bat --theme ansi"
