---

- name: Install better greps
  package:
    name:
      - bat
      - difftastic
      - direnv
      - eza
      - fd-find
      - fzf
      - ripgrep
      - the_silver_searcher
    state: present
