---
- name: Install alacritty
  package:
    state: present
    name: alacritty

- name: Create configuration folder
  become: yes
  become_user: "{{ desktop_user.username }}"
  file:
    state: directory
    dest: "~/.config/alacritty"

- name: Create theme folder
  become: yes
  become_user: "{{ desktop_user.username }}"
  git:
    repo: https://github.com/alacritty/alacritty-theme.git
    dest: "~/.config/alacritty/themes"
    update: yes

- name: Copy alacritty configuration
  become: yes
  become_user: "{{ desktop_user.username }}"
  copy:
    src: "alacritty.toml"
    dest: "~/.config/alacritty/alacritty.toml"
