---
- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - gnupg
    - pcsc-tools
    - pcsclite
    - ccid

- name: Enable pcscd socket
  service:
    name: pcscd.socket
    state: started
    enabled: true
