---

- name: Install distribution specific
  include_tasks: "install_{{ ansible_os_family }}.yml"

- name: Import own public key
  become: yes
  become_user: "{{ desktop_user.username }}"
  command: gpg --no-tty --recv-keys "{{ desktop_user.gpgkey }}"
  when: desktop_user.gpgkey

- name: Trust own key ultimately
  become: yes
  become_user: "{{ desktop_user.username }}"
  shell: echo "{{ desktop_user.gpgkey }}:6:" | gpg --import-ownertrust
  when: desktop_user.gpgkey
