---
# Instead of trying to shoehorn windows specific setups into the normal main.yml
# file use a separate windows file for each role.
- name: Install gpg on windows
  win_chocolatey:
    name: gpg4win
    state: present

#  - name: Install npiperelay
#    TODO: must compile https://github.com/jstarks/npiperelay/pull/6 for libasuan support

- name: Import the gpg-key
  win_command: gpg --no-tty --recv-keys "{{ desktop_user.gpgkey }}"
  when: desktop_user.gpgkey

- name: Trust the gpg-key ultimately
  win_shell: echo "{{ desktop_user.gpgkey }}:6:" | gpg --import-ownertrust
  when: desktop_user.gpgkey

- name: Put gpg-agent into autostart
  win_shortcut:
    src: "%ProgramFiles(x86)%\\GnuPG\\bin\\gpg-connect-agent.exe"
    dest: "%AppData%\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\gpg-connect-agent.lnk"
    directory: "%ProgramFiles%\\GnuPG\\bin\\"
    arguments: "/bye"
    windowstyle: minimized
